export const mockFlowers = [
    { id: 1, name: "Rose", scientificName: "Rosa", familyCommonName: "Rose Family", imageUrl: null },
    { id: 2, name: "Tulip", scientificName: "Tulipa", familyCommonName: "Lily Family", imageUrl: null },
    { id: 3, name: "Daisy", scientificName: "Bellis perennis", familyCommonName: "Asteraceae", imageUrl: null },
    { id: 4, name: "Sunflower", scientificName: "Helianthus annuus", familyCommonName: "Asteraceae", imageUrl: null },
    { id: 5, name: "Lily", scientificName: "Lilium", familyCommonName: "Lily Family", imageUrl: null },
    { id: 6, name: "Orchid", scientificName: "Orchidaceae", familyCommonName: "Orchid Family", imageUrl: null },
    { id: 7, name: "Carnation", scientificName: "Dianthus caryophyllus", familyCommonName: "Carnation Family", imageUrl: null },
    { id: 8, name: "Iris", scientificName: "Iris germanica", familyCommonName: "Iridaceae", imageUrl: null },
    { id: 9, name: "Daffodil", scientificName: "Narcissus", familyCommonName: "Amaryllidaceae", imageUrl: null },
    { id: 10, name: "Violet", scientificName: "Viola", familyCommonName: "Violaceae", imageUrl: null },
    { id: 11, name: "Chrysanthemum", scientificName: "Chrysanthemum", familyCommonName: "Asteraceae", imageUrl: null },
    { id: 12, name: "Lavender", scientificName: "Lavandula", familyCommonName: "Lamiaceae", imageUrl: null },
    { id: 13, name: "Marigold", scientificName: "Tagetes", familyCommonName: "Asteraceae", imageUrl: null },
    { id: 14, name: "Poppy", scientificName: "Papaver somniferum", familyCommonName: "Papaveraceae", imageUrl: null },
    { id: 15, name: "Zinnia", scientificName: "Zinnia elegans", familyCommonName: "Asteraceae", imageUrl: null },
    { id: 16, name: "Begonia", scientificName: "Begonia", familyCommonName: "Begoniaceae", imageUrl: null },
    { id: 17, name: "Freesia", scientificName: "Freesia", familyCommonName: "Iridaceae", imageUrl: null },
    { id: 18, name: "Geranium", scientificName: "Pelargonium", familyCommonName: "Geraniaceae", imageUrl: null },
    { id: 19, name: "Camellia", scientificName: "Camellia japonica", familyCommonName: "Theaceae", imageUrl: null },
    { id: 20, name: "Tulip", scientificName: "Tulipa", familyCommonName: "Lily Family", imageUrl: null },
];
